# Integrantes: Alejandro Vargas Rodríguez y Juan Pablo Ríos.
defmodule Datos do
  @moduledoc "Datos del grupo: 10 repartidores, 4 zonas, 108 servicios válidos y 10 inválidos."
  @doc "Repartidores; M10 no tiene servicios para comprobar una liquidación en cero."
  def repartidores do
    [
      %{codigo: "M01", nombre: "Ana Torres", bicicleta: true},
      %{codigo: "M02", nombre: "David López", bicicleta: true},
      %{codigo: "M03", nombre: "Camila Pérez", bicicleta: true},
      %{codigo: "M04", nombre: "Luis Gómez", bicicleta: true},
      %{codigo: "M05", nombre: "Sofía Martínez", bicicleta: false},
      %{codigo: "M06", nombre: "Mateo Ruiz", bicicleta: false},
      %{codigo: "M07", nombre: "Valentina Díaz", bicicleta: false},
      %{codigo: "M08", nombre: "Daniel Castro", bicicleta: false},
      %{codigo: "M09", nombre: "Laura Moreno", bicicleta: false},
      %{codigo: "M10", nombre: "Santiago Herrera", bicicleta: true}
    ]
  end

  @doc "Cuatro zonas y sus áreas en kilómetros cuadrados."
  def zonas do
    [
      %{id: "Z1", nombre: "Centro", area: 6.5},
      %{id: "Z2", nombre: "Norte", area: 10.2},
      %{id: "Z3", nombre: "Sur", area: 8.0},
      %{id: "Z4", nombre: "Occidente", area: 12.5}
    ]
  end

  @doc "Servicios de los seis días; los últimos diez registros son rechazos intencionales."
  def servicios do
    [
      %{repartidor: "M01", zona: "Z1", dia: 1, kilometros: 40, retraso: 0},
      %{repartidor: "M01", zona: "Z2", dia: 1, kilometros: 40, retraso: 3},
      %{repartidor: "M02", zona: "Z2", dia: 1, kilometros: 40, retraso: 3},
      %{repartidor: "M02", zona: "Z3", dia: 1, kilometros: 40, retraso: 10},
      %{repartidor: "M03", zona: "Z3", dia: 1, kilometros: 40, retraso: 10},
      %{repartidor: "M03", zona: "Z4", dia: 1, kilometros: 40, retraso: 11},
      %{repartidor: "M04", zona: "Z4", dia: 1, kilometros: 40, retraso: 11},
      %{repartidor: "M04", zona: "Z1", dia: 1, kilometros: 40, retraso: 20},
      %{repartidor: "M05", zona: "Z1", dia: 1, kilometros: 40, retraso: 20},
      %{repartidor: "M05", zona: "Z2", dia: 1, kilometros: 40, retraso: 30},
      %{repartidor: "M06", zona: "Z2", dia: 1, kilometros: 40, retraso: 30},
      %{repartidor: "M06", zona: "Z3", dia: 1, kilometros: 40, retraso: 31},
      %{repartidor: "M07", zona: "Z3", dia: 1, kilometros: 40, retraso: 31},
      %{repartidor: "M07", zona: "Z4", dia: 1, kilometros: 40, retraso: 60},
      %{repartidor: "M08", zona: "Z4", dia: 1, kilometros: 40, retraso: 60},
      %{repartidor: "M08", zona: "Z1", dia: 1, kilometros: 40, retraso: 180},
      %{repartidor: "M09", zona: "Z1", dia: 1, kilometros: 40, retraso: 180},
      %{repartidor: "M09", zona: "Z2", dia: 1, kilometros: 40, retraso: 2.5},
      %{repartidor: "M01", zona: "Z2", dia: 2, kilometros: 45, retraso: 3},
      %{repartidor: "M01", zona: "Z3", dia: 2, kilometros: 39, retraso: 10},
      %{repartidor: "M02", zona: "Z3", dia: 2, kilometros: 45, retraso: 10},
      %{repartidor: "M02", zona: "Z4", dia: 2, kilometros: 39, retraso: 11},
      %{repartidor: "M03", zona: "Z4", dia: 2, kilometros: 45, retraso: 11},
      %{repartidor: "M03", zona: "Z1", dia: 2, kilometros: 39, retraso: 20},
      %{repartidor: "M04", zona: "Z1", dia: 2, kilometros: 45, retraso: 20},
      %{repartidor: "M04", zona: "Z2", dia: 2, kilometros: 39, retraso: 30},
      %{repartidor: "M05", zona: "Z2", dia: 2, kilometros: 45, retraso: 30},
      %{repartidor: "M05", zona: "Z3", dia: 2, kilometros: 39, retraso: 31},
      %{repartidor: "M06", zona: "Z3", dia: 2, kilometros: 45, retraso: 31},
      %{repartidor: "M06", zona: "Z4", dia: 2, kilometros: 39, retraso: 60},
      %{repartidor: "M07", zona: "Z4", dia: 2, kilometros: 45, retraso: 60},
      %{repartidor: "M07", zona: "Z1", dia: 2, kilometros: 39, retraso: 180},
      %{repartidor: "M08", zona: "Z1", dia: 2, kilometros: 45, retraso: 180},
      %{repartidor: "M08", zona: "Z2", dia: 2, kilometros: 39, retraso: 2.5},
      %{repartidor: "M09", zona: "Z2", dia: 2, kilometros: 45, retraso: 2.5},
      %{repartidor: "M09", zona: "Z3", dia: 2, kilometros: 39, retraso: -30},
      %{repartidor: "M01", zona: "Z3", dia: 3, kilometros: 38.5, retraso: 10},
      %{repartidor: "M01", zona: "Z4", dia: 3, kilometros: 41.5, retraso: 11},
      %{repartidor: "M02", zona: "Z4", dia: 3, kilometros: 38.5, retraso: 11},
      %{repartidor: "M02", zona: "Z1", dia: 3, kilometros: 41.5, retraso: 20},
      %{repartidor: "M03", zona: "Z1", dia: 3, kilometros: 38.5, retraso: 20},
      %{repartidor: "M03", zona: "Z2", dia: 3, kilometros: 41.5, retraso: 30},
      %{repartidor: "M04", zona: "Z2", dia: 3, kilometros: 38.5, retraso: 30},
      %{repartidor: "M04", zona: "Z3", dia: 3, kilometros: 41.5, retraso: 31},
      %{repartidor: "M05", zona: "Z3", dia: 3, kilometros: 38.5, retraso: 31},
      %{repartidor: "M05", zona: "Z4", dia: 3, kilometros: 41.5, retraso: 60},
      %{repartidor: "M06", zona: "Z4", dia: 3, kilometros: 38.5, retraso: 60},
      %{repartidor: "M06", zona: "Z1", dia: 3, kilometros: 41.5, retraso: 180},
      %{repartidor: "M07", zona: "Z1", dia: 3, kilometros: 38.5, retraso: 180},
      %{repartidor: "M07", zona: "Z2", dia: 3, kilometros: 41.5, retraso: 2.5},
      %{repartidor: "M08", zona: "Z2", dia: 3, kilometros: 38.5, retraso: 2.5},
      %{repartidor: "M08", zona: "Z3", dia: 3, kilometros: 41.5, retraso: -30},
      %{repartidor: "M09", zona: "Z3", dia: 3, kilometros: 38.5, retraso: -30},
      %{repartidor: "M09", zona: "Z4", dia: 3, kilometros: 41.5, retraso: -5},
      %{repartidor: "M01", zona: "Z4", dia: 4, kilometros: 35, retraso: 11},
      %{repartidor: "M01", zona: "Z1", dia: 4, kilometros: 44, retraso: 20},
      %{repartidor: "M02", zona: "Z1", dia: 4, kilometros: 35, retraso: 20},
      %{repartidor: "M02", zona: "Z2", dia: 4, kilometros: 44, retraso: 30},
      %{repartidor: "M03", zona: "Z2", dia: 4, kilometros: 35, retraso: 30},
      %{repartidor: "M03", zona: "Z3", dia: 4, kilometros: 44, retraso: 31},
      %{repartidor: "M04", zona: "Z3", dia: 4, kilometros: 35, retraso: 31},
      %{repartidor: "M04", zona: "Z4", dia: 4, kilometros: 44, retraso: 60},
      %{repartidor: "M05", zona: "Z4", dia: 4, kilometros: 35, retraso: 60},
      %{repartidor: "M05", zona: "Z1", dia: 4, kilometros: 44, retraso: 180},
      %{repartidor: "M06", zona: "Z1", dia: 4, kilometros: 35, retraso: 180},
      %{repartidor: "M06", zona: "Z2", dia: 4, kilometros: 44, retraso: 2.5},
      %{repartidor: "M07", zona: "Z2", dia: 4, kilometros: 35, retraso: 2.5},
      %{repartidor: "M07", zona: "Z3", dia: 4, kilometros: 44, retraso: -30},
      %{repartidor: "M08", zona: "Z3", dia: 4, kilometros: 35, retraso: -30},
      %{repartidor: "M08", zona: "Z4", dia: 4, kilometros: 44, retraso: -5},
      %{repartidor: "M09", zona: "Z4", dia: 4, kilometros: 35, retraso: -5},
      %{repartidor: "M09", zona: "Z1", dia: 4, kilometros: 44, retraso: 0},
      %{repartidor: "M01", zona: "Z1", dia: 5, kilometros: 42, retraso: 20},
      %{repartidor: "M01", zona: "Z2", dia: 5, kilometros: 40.5, retraso: 30},
      %{repartidor: "M02", zona: "Z2", dia: 5, kilometros: 42, retraso: 30},
      %{repartidor: "M02", zona: "Z3", dia: 5, kilometros: 40.5, retraso: 31},
      %{repartidor: "M03", zona: "Z3", dia: 5, kilometros: 42, retraso: 31},
      %{repartidor: "M03", zona: "Z4", dia: 5, kilometros: 40.5, retraso: 60},
      %{repartidor: "M04", zona: "Z4", dia: 5, kilometros: 42, retraso: 60},
      %{repartidor: "M04", zona: "Z1", dia: 5, kilometros: 40.5, retraso: 180},
      %{repartidor: "M05", zona: "Z1", dia: 5, kilometros: 42, retraso: 180},
      %{repartidor: "M05", zona: "Z2", dia: 5, kilometros: 40.5, retraso: 2.5},
      %{repartidor: "M06", zona: "Z2", dia: 5, kilometros: 42, retraso: 2.5},
      %{repartidor: "M06", zona: "Z3", dia: 5, kilometros: 40.5, retraso: -30},
      %{repartidor: "M07", zona: "Z3", dia: 5, kilometros: 42, retraso: -30},
      %{repartidor: "M07", zona: "Z4", dia: 5, kilometros: 40.5, retraso: -5},
      %{repartidor: "M08", zona: "Z4", dia: 5, kilometros: 42, retraso: -5},
      %{repartidor: "M08", zona: "Z1", dia: 5, kilometros: 40.5, retraso: 0},
      %{repartidor: "M09", zona: "Z1", dia: 5, kilometros: 42, retraso: 0},
      %{repartidor: "M09", zona: "Z2", dia: 5, kilometros: 40.5, retraso: 3},
      %{repartidor: "M01", zona: "Z2", dia: 6, kilometros: 18, retraso: 30},
      %{repartidor: "M01", zona: "Z3", dia: 6, kilometros: 22, retraso: 31},
      %{repartidor: "M02", zona: "Z3", dia: 6, kilometros: 18, retraso: 31},
      %{repartidor: "M02", zona: "Z4", dia: 6, kilometros: 22, retraso: 60},
      %{repartidor: "M03", zona: "Z4", dia: 6, kilometros: 18, retraso: 60},
      %{repartidor: "M03", zona: "Z1", dia: 6, kilometros: 22, retraso: 180},
      %{repartidor: "M04", zona: "Z1", dia: 6, kilometros: 18, retraso: 180},
      %{repartidor: "M04", zona: "Z2", dia: 6, kilometros: 22, retraso: 2.5},
      %{repartidor: "M05", zona: "Z2", dia: 6, kilometros: 18, retraso: 2.5},
      %{repartidor: "M05", zona: "Z3", dia: 6, kilometros: 22, retraso: -30},
      %{repartidor: "M06", zona: "Z3", dia: 6, kilometros: 18, retraso: -30},
      %{repartidor: "M06", zona: "Z4", dia: 6, kilometros: 22, retraso: -5},
      %{repartidor: "M07", zona: "Z4", dia: 6, kilometros: 18, retraso: -5},
      %{repartidor: "M07", zona: "Z1", dia: 6, kilometros: 22, retraso: 0},
      %{repartidor: "M08", zona: "Z1", dia: 6, kilometros: 18, retraso: 0},
      %{repartidor: "M08", zona: "Z2", dia: 6, kilometros: 22, retraso: 3},
      %{repartidor: "M09", zona: "Z2", dia: 6, kilometros: 18, retraso: 3},
      %{repartidor: "M09", zona: "Z3", dia: 6, kilometros: 22, retraso: 10},
      %{repartidor: "M99", zona: "Z1", dia: 1, kilometros: 10, retraso: 0},
      %{repartidor: "M98", zona: "Z99", dia: 7, kilometros: 0, retraso: 181},
      %{repartidor: "M01", zona: "Z99", dia: 1, kilometros: 10, retraso: 0},
      %{repartidor: "M02", zona: "Z98", dia: 0, kilometros: 46, retraso: 181},
      %{repartidor: "M01", zona: "Z1", dia: 0, kilometros: 10, retraso: 0},
      %{repartidor: "M02", zona: "Z2", dia: 2.5, kilometros: 46, retraso: 181},
      %{repartidor: "M01", zona: "Z1", dia: 1, kilometros: 0, retraso: 0},
      %{repartidor: "M02", zona: "Z2", dia: 2, kilometros: 45.1, retraso: 181},
      %{repartidor: "M01", zona: "Z1", dia: 1, kilometros: 10, retraso: -30.1},
      %{repartidor: "M02", zona: "Z2", dia: 2, kilometros: 10, retraso: 180.1}
    ]
  end
end 
